services:
    php-apache:
        container_name: gensokyo-php-apache
        build:
            context: './'
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html             # Public files
            - ./src/configs:/var/www/configs      # Private configs
        ports:
            - 8000:80
        restart: unless-stopped
        mem_limit: 1g
    mariadb:
        container_name: gensokyo-mariadb
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mariadb_data:/var/lib/mysql
        restart: unless-stopped
        mem_limit: 512m
    phpmyadmin:
        container_name: gensokyo-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        restart: unless-stopped
        mem_limit: 256m
