services:
    php-apache:
        container_name: gensokyo-php-apache
        build:
            context: './'
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html             # Public files
            - ./src/configs:/var/www/configs      # Private configs
        ports:
            - 84:80
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: unless-stopped
        mem_limit: 1g
        extra_hosts:
            - "host.docker.internal:host-gateway"
